<ul class="collection">
	<li class="collection-item"><a href="">Link item 1</a></li>
	<li class="collection-item"><a href="">Link item 2</a></li>
	<li class="collection-item"><a href="">Link item 3</a></li>
	<li class="collection-item"><a href="">Link item 4</a></li>
	<li class="collection-item"><a href="">Link item 5</a></li>
	<li class="collection-item"><a href="">Link item 6</a></li>
	<li class="collection-item"><a href="">Link item 7</a></li>
	<li class="collection-item"><a href="">Link item 8</a></li>
	<li class="collection-item"><a href="">Link item 9</a></li>
	<li class="collection-item"><a href="">Link item 10</a></li>
	<li class="collection-item"><a href="">Link item 11</a></li>
	<li class="collection-item"><a href="">Link item 12</a></li>
	<li class="collection-item"><a href="">Link item 13</a></li>
	<li class="collection-item"><a href="">Link item 14</a></li>
	<li class="collection-item"><a href="">Link item 15</a></li>
	<li class="collection-item"><a href="">Link item 16</a></li>
	<li class="collection-item"><a href="">Link item 17</a></li>
	<li class="collection-item"><a href="">Link item 18</a></li>
	<li class="collection-item"><a href="">Link item 19</a></li>
	<li class="collection-item"><a href="">Link item 20</a></li>
	<li class="collection-item"><a href="">Link item 21</a></li>
	<li class="collection-item"><a href="">Link item 22</a></li>
	<li class="collection-item"><a href="">Link item 23</a></li>
	<li class="collection-item"><a href="">Link item 24</a></li>
	<li class="collection-item"><a href="">Link item 25</a></li>
	<li class="collection-item"><a href="">Link item 26</a></li>
	<li class="collection-item"><a href="">Link item 27</a></li>
	<li class="collection-item"><a href="">Link item 28</a></li>
	<li class="collection-item"><a href="">Link item 29</a></li>
	<li class="collection-item"><a href="">Link item 30</a></li>
	<li class="collection-item"><a href="">Link item 31</a></li>
	<li class="collection-item"><a href="">Link item 32</a></li>
	<li class="collection-item"><a href="">Link item 33</a></li>
	<li class="collection-item"><a href="">Link item 34</a></li>
	<li class="collection-item"><a href="">Link item 35</a></li>
	<li class="collection-item"><a href="">Link item 36</a></li>
	<li class="collection-item"><a href="">Link item 37</a></li>
	<li class="collection-item"><a href="">Link item 38</a></li>
	<li class="collection-item"><a href="">Link item 39</a></li>
	<li class="collection-item"><a href="">Link item 40</a></li>
	<li class="collection-item"><a href="">Link item 41</a></li>
	<li class="collection-item"><a href="">Link item 42</a></li>
	<li class="collection-item"><a href="">Link item 43</a></li>
	<li class="collection-item"><a href="">Link item 44</a></li>
	<li class="collection-item"><a href="">Link item 45</a></li>
	<li class="collection-item"><a href="">Link item 46</a></li>
	<li class="collection-item"><a href="">Link item 47</a></li>
	<li class="collection-item"><a href="">Link item 48</a></li>
	<li class="collection-item"><a href="">Link item 49</a></li>
	<li class="collection-item"><a href="">Link item 50</a></li>
</ul>
